# git-cliff configuration - generates CHANGELOG.md from commit messages
# Adjust `types` and `title` sections to match your commit message conventions


[changelog]
header = "Changelog"
body = """
{%- macro remote_url() -%}
	https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
		- {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
				{% if commit.breaking %}[**ç ´åæ€§æ›´æ”¹**] {% endif %}\
				{{ commit.message | upper_first }}\
{% endmacro -%}

{% for group, commits in commits | group_by(attribute="group") %}
		## {{ group | striptags | trim | upper_first }}
		{% for commit in commits
		| filter(attribute="scope")
		| sort(attribute="scope") %}
				{{ self::print_commit(commit=commit) }}
		{%- endfor %}
		{% for commit in commits %}
				{%- if not commit.scope -%}
						{{ self::print_commit(commit=commit) }}
				{% endif -%}
		{% endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | length != 0 %}
	## è´¡çŒ®è€…

	æ„Ÿè°¢ä»¥ä¸‹è´¡çŒ®è€…çš„è´¡çŒ®ï¼š

{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
	- @{{ contributor.username }}
{%- endfor -%}
{%- endif %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"
postprocessors = [{ pattern = "#([0-9]+)", replace = "([#${1}](https://github.com/iCurrer/OMaster/issues/${1}))"}]

[git]
commit_parsers = [
	{ message = "^feat", group = "<!-- 0 -->ğŸš€ æ–°å¢åŠŸèƒ½ä¸ä¼˜åŒ–" },
	{ message = "^fix", group = "<!-- 1 -->ğŸ› Bug ä¿®å¤" },
	{ message = "^perf", group = "<!-- 0 -->ğŸš€ æ–°å¢åŠŸèƒ½ä¸ä¼˜åŒ–" },
	{ message = "^security", group = "<!-- 2 -->ğŸ”’ å®‰å…¨ä¿®å¤" },
	{ message = "^docs", group = "<!-- 3 -->ğŸ“š æ–‡æ¡£æ›´æ–°" },
	{ message = "^build", group = "<!-- 4 -->ğŸ”§ æ„å»ºç³»ç»Ÿ" },
	{ message = "^ci", group = "<!-- 4 -->ğŸ”§ æ„å»ºç³»ç»Ÿ" },
	{ message = "^revert", group = "<!-- 9 -->â—€ï¸ å›æ»šçš„åŠŸèƒ½" },
]
conventional_commits = true
filter_unconventional = false
split_commits = false
protect_breaking_commits = false
remote = "origin"

[remote.github]
owner = "iCurrer"
repo = "OMaster"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
